### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Pauldro** [cptechinc/soft-6-ecomm#28]
We’ll need to develop a login screen, 
Account screen,
The login screen should both have the form and also take input to login 
I have have a function called userlogin() to have this work.  Should be in dplus.php
So we need a function in  _dbfunc.php for checking if login is valid in the login table. 
Based off the user login you’ll make a user logout as well in _dplus.php

**Comment by Pauldro** [comment]
I have the `userlogin($sessionID, $email, $password)` function on the **/user/redir/** page (look in processwire to find out what file this is working from) working,
I have init looking for if logged in and the variable it saves it to is $user->loggedin,

Now, your account page, should look for if user is logged in or not and if not, it should redirect them to the login page. Once you know what redir file the **/user/redir/** page is using add ability to logout the user.
The function to actually log out should be added to _dplus.php, look at the `writeloginrecord()` for a semi-example.

**Comment by bbullemer** [comment]
I created commits for this issue and forgot to add the issue number to the title.

**Comment by Pauldro** [comment]
@bbullemer If you can get the commit IDs (SHA) and just paste them in a comment, or you can't that's fine. Just remember to tie commits to issues when you applicable.

**Comment by bbullemer** [comment]
58c418b046d689be683cc7186211c8faea9a8faf
cf823668a7b1d63c4e0b9ef5a30af4bc5550d82b
88494b92326a2b746ae2c40b44560e300bcfd642
